# Generated by Django 5.2.18 on 2026-10-09 08:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('submitted', 'Submitted (payments disabled)'), ('pending', 'Awaiting payment'), ('paid', 'Paid')], default='submitted', max_length=16)),
                ('amount_pence', models.PositiveIntegerField(default=3900, editable=False)),
                ('currency', models.CharField(default='gbp', editable=False, max_length=3)),
                ('stripe_session_id', models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
