# Generated by Django 5.2.18 on 2026-10-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_birthrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthrequest',
            name='report_sent',
            field=models.BooleanField(default=False, help_text='Mark this after manually emailing the report.'),
        ),
        migrations.AddField(
            model_name='birthrequest',
            name='source',
            field=models.CharField(choices=[('storefront', 'Storefront'), ('promotion', 'Free promotion')], default='storefront', max_length=16),
        ),
        migrations.AlterField(
            model_name='birthrequest',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted (payments disabled)'), ('pending', 'Awaiting payment'), ('paid', 'Paid'), ('free', 'Free redemption')], default='submitted', max_length=16),
        ),
    ]
