# Generated by Django 5.2.18 on 2026-10-09 11:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_alter_feedback_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='birth_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='studio.birthrequest'),
        ),
        migrations.CreateModel(
            name='ChartEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient', models.EmailField(max_length=254)),
                ('sender', models.EmailField(max_length=254)),
                ('reply_to', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('pdf_sha256', models.CharField(max_length=64)),
                ('provider_id', models.CharField(blank=True, max_length=255)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('birth_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chart_emails', to='studio.birthrequest')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studio.report')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
