# Generated by Django 5.2.18 on 2026-10-09 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0006_report_birth_request_chartemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, validators=[django.core.validators.RegexValidator('^[^\\s@]+@(?:[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?\\.)+[A-Za-z]{2,63}$', 'Enter a complete email address, for example name@example.com.')]),
        ),
        migrations.AlterField(
            model_name='chartemail',
            name='recipient',
            field=models.EmailField(max_length=254, validators=[django.core.validators.RegexValidator('^[^\\s@]+@(?:[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?\\.)+[A-Za-z]{2,63}$', 'Enter a complete email address, for example name@example.com.')]),
        ),
        migrations.AlterField(
            model_name='chartemail',
            name='reply_to',
            field=models.EmailField(blank=True, max_length=254, validators=[django.core.validators.RegexValidator('^[^\\s@]+@(?:[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?\\.)+[A-Za-z]{2,63}$', 'Enter a complete email address, for example name@example.com.')]),
        ),
        migrations.AlterField(
            model_name='chartemail',
            name='sender',
            field=models.EmailField(max_length=254, validators=[django.core.validators.RegexValidator('^[^\\s@]+@(?:[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?\\.)+[A-Za-z]{2,63}$', 'Enter a complete email address, for example name@example.com.')]),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.RegexValidator('^[^\\s@]+@(?:[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?\\.)+[A-Za-z]{2,63}$', 'Enter a complete email address, for example name@example.com.')]),
        ),
    ]
