# Generated by Django 5.2.18 on 2026-10-09 12:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


def assign_removal_tokens(apps, schema_editor):
    model = apps.get_model("studio", "BirthRequest")
    for customer in model.objects.using(schema_editor.connection.alias).all().iterator():
        model.objects.using(schema_editor.connection.alias).filter(pk=customer.pk).update(removal_token=uuid.uuid4())



class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0007_alter_birthrequest_email_alter_chartemail_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthrequest',
            name='removal_token',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='birth_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studio.birthrequest'),
        ),
        migrations.AddField(
            model_name='review',
            name='birth_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studio.birthrequest'),
        ),
        migrations.CreateModel(
            name='DataRemovalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('birth_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='studio.birthrequest')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.RunPython(assign_removal_tokens, migrations.RunPython.noop),
        migrations.AlterField(model_name='birthrequest', name='removal_token', field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False)),
    ]
