# Generated by Django 5.2.18 on 2026-10-09 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0008_birthrequest_removal_token_feedback_birth_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthrequest',
            name='payment_mode',
            field=models.CharField(choices=[('demo', 'Local demo'), ('test', 'Stripe test'), ('live', 'Live payment')], default='test', max_length=8),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateTimeField()),
                ('customer', models.JSONField()),
                ('issuer', models.JSONField()),
                ('total_pence', models.PositiveIntegerField()),
                ('vat_pence', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='gbp', max_length=3)),
                ('is_test', models.BooleanField(default=True)),
                ('birth_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='studio.birthrequest')),
            ],
        ),
    ]
