# Generated by Django 5.2.18 on 2026-10-09 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0009_birthrequest_payment_mode_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthrequest',
            name='delivery_consent',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='contract_terms',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='birth_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='studio.birthrequest'),
        ),
    ]
