# Generated by Django 5.2.18 on 2026-10-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0010_birthrequest_delivery_consent_invoice_contract_terms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='line_items',
            field=models.JSONField(default=list),
        ),
    ]
