# Generated by Django 5.2.18 on 2026-10-09 14:15

from django.db import migrations


def backfill_snapshots(apps, schema_editor):
    Invoice = apps.get_model('studio', 'Invoice')
    for invoice in Invoice.objects.using(schema_editor.connection.alias).select_related('birth_request').iterator():
        changed = []
        if not invoice.line_items:
            net = invoice.total_pence - invoice.vat_pence
            invoice.line_items = [{'description': 'Personalised natal chart PDF', 'quantity': 1, 'unit_net_pence': net, 'line_net_pence': net}]
            changed.append('line_items')
        if not invoice.payment_reference and invoice.birth_request_id:
            invoice.payment_reference = invoice.birth_request.stripe_session_id or ''
            changed.append('payment_reference')
        if changed:
            invoice.save(update_fields=changed)


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0011_invoice_line_items'),
    ]

    operations = [
        migrations.RunPython(backfill_snapshots, migrations.RunPython.noop),
    ]
